spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///xzzj_bbs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 7069
    database: 1
xzzj:
  imgPath:
  local: localhost:9400