spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.3.170.239:3306/xzzj_bbs?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: kuaile09-20
  main:
    allow-bean-definition-overriding: true
  redis:
    host: localhost
    port: 6379
    database: 0

xzzj:
  imgPath: /usr/local/src/server/static/images/
  local: 119.3.170.239
